### ISSUE TITLE
Implémenter les recommandations google search

### ISSUE THREAD

**Issue by mdautrey** [shipmaintenance/staticsite#57]

**Comment by pjtiberghien** [comment]
![Recommandation_google.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a4ca058327fcd0012635889/125516c66e82c728ace21e0d46da91992c8f8ea881edbe57ad52feab2e4928742501e1673295f127b54778154d555ca910590b42fefd8e7da6b73d768c5c0ae5856a0d21c33816bea4905dee5fee7fd616cfe3fe9846d2e9352fe68e8d4c3d19031f8efe5a3ca18b06.png)

**Comment by pjtiberghien** [comment]
Voici le résultat du test fait ce jour.
Je vais travailler sur l'optimisation des images.
